name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: x86
    container:
      image: gitea.gregorlohaus.com/gregor/graal:latest
      credentials:
        username: lohausgregor@gmail.com
        password: ${{ secrets.REGPASS }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: /usr/local/bin/docker-entrypoint.sh postgres &
      - name: build
        working-directory: ${{ gitea.workspace }}/Backend
        env:
          JAVA_HOME: /root/.sdkman/candidates/java/current 
        run: /root/.sdkman/candidates/gradle/9.4.0/bin/gradle build 
      - name: upload binary
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: gtransfer
          path: ${{ gitea.workspace }}/Backend/build/native/nativeCompile/gtransfer
